version: '3.4'

services:
  postgres:
    image: postgres:10.4
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ticket_checker
      POSTGRES_USER: ticketUser
      POSTGRES_PASSWORD: 123456987asd

  build:
      image: ticket-checker-server-build:1.0
      entrypoint:
        - "true"
      build:
        context: .
        target: build

  server:
      image: ticket-checker-server:1.0
      build:
        context: .
      restart: unless-stopped
      ports:
      - 8080:8080
      links:
      - postgres
      depends_on:
      - postgres